---
title: "Learning R and R-Studio for Education and Social Science Research"
author: "Fernando Rodriguez and Hye Rin Lee"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This book will teach you how to use the R programming language for education and psychological sciences."
---

# Introduction

We are looking forward to introducing you to the wonderful world of R and RStudio.

R is a very powerful statistical programming language that has several advantages over using Stata or SPSS. The most obvious is that R is completely free. Another great feature about R is that there are several add-on programs, such as the R-Studio, which helps us better manage multiple datasets at the same time and share reproducible code. 

The downside of using R is that it almost exclusively code-based, meaning that there are very limited point-and-click features. In order to get R to perform an analysis or plot a figure, you have to write several lines of code, which can feel like a big barrier if you are unfamiliar with programming concepts.

The goal of this book is to ease you into learning how to program in R and use RStudio to optimize your data workflow. What makes this book different from others is that we assume you have zero experience with using R and RStudio (and are also a bit intimidated by learning it!), so everything is explained as straightforward as possible. 

Moreover, the book will guide you through the entire process of analyzing educational data obtained from an online STEM course. This includes importing, inspecting, making decisions about your sample size, generating descriptive data, creating data visualizations, and using inferential statistics to draw conclusions from your sample. By the end of this book, you will have the necessary proficiency to use R and RStudio on your own research project from start to finish.

As you work your way through the chapters, you will find that programming in R is much easier than it looks. You will also appreciate how R-Studio helps us manage research projects. Even more exciting, once you get a good sense of some of the basics, you will soon begin tinkering with code and try things just for the sake of trying things out. That's where the real fun starts.

## Who is this book for?

We wrote this book for people who do education or social science research, who are at various levels in their careers, and who want a easy-to-follow book for learning R and RStudio. This includes undergraduate lab assistants who are conducting research for the first time, graduate students, faculty, and seasoned researchers who know how to use SPSS or Stata, but want to branch out to and expand their skills.

While no experience with R or RStudio or coding is necessary, we do assume that you have a basic understanding of research methods and statistics.

## Structure of the book

This book consists of three parts. `Part I` walks you through installing R, which is the actual program we need to have open in order to run code in RStudio, which is a graphical user interface (GUI) that helps us better manage our project files and datasets. We will then walk you through the most basic concepts surrounding the R programming language, as well as popular libraries. Libraries refer to a suite of features we can use in R, but are not part of the main R program. Finally, because we want you to see the immediate appeal of using R and RStudio, you will also write your first data visualization code.

`Part II` will guide you through importing, inspecting, and exploring your data. It is here you will learn all about the 'tidy' method for working with data. This 'tidy' method was developed by Hadley Wickham along with the RStudio team, and it refers to a principles for working with data.

`Part III` will help you understand how to conduct inferential statistics, and.....

## Additional resources

While is this book provides a general introduction to using R and RStudio, we don't cover everything we think you should know about RStudio, so we recommend that you refer the following books:

## About the authors

Fernando Rodriguez, Ph.D., is an assistant professor of teaching in the School of Education at the University of California, Irvine. He enjoys teaching various undergraduate-level courses and the graduate-level statistics course in the School of Education. His research focuses on learning analytics and higher-order thinking skills. Dr. Rodriguez earned his B.A. in Psychology from California State University, Northridge. He earned his Master's degree in Developmental Psychology and his Ph.D. in Educational Psychology from the University of Michigan, Ann Arbor.

Hye Rin Lee is a doctoral candidate in the School of Education at the University of California, Irvine, with a concentration in Human Development in Context. Hye Rin received her B.A. in Psychology and Sociology from Franklin and Marshall College. Hye Rin’s research interests broadly focuses on academic motivation in school settings. Specifically, her research interests are situated in the intersections of STEM education, media technologies, and higher education. Outside of academia, she likes to watch movies and explore innovative places.

## Acknowledgments

We would like to thank the National Science Foundation (Grant Number 1535300) and the Institute for Education Sciences (Grant Number R305B210006) for supporting the development of this book. 
