<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 CHAPTER 1 | R Workshop for Education Data Science Lesson 1</title>
  <meta name="description" content="This book will teach you how to use the R programming language for learning analytics research." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 CHAPTER 1 | R Workshop for Education Data Science Lesson 1" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book will teach you how to use the R programming language for learning analytics research." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 CHAPTER 1 | R Workshop for Education Data Science Lesson 1" />
  
  <meta name="twitter:description" content="This book will teach you how to use the R programming language for learning analytics research." />
  

<meta name="author" content="Fernando Rodriguez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>
<link rel="next" href="references.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Prerequisites</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="chapter-1.html"><a href="chapter-1.html"><i class="fa fa-check"></i><b>3</b> CHAPTER 1</a>
<ul>
<li class="chapter" data-level="3.1" data-path="chapter-1.html"><a href="chapter-1.html#loading-libraries"><i class="fa fa-check"></i><b>3.1</b> Loading Libraries</a></li>
<li class="chapter" data-level="3.2" data-path="chapter-1.html"><a href="chapter-1.html#creating-code-chunks-in-r-markdown"><i class="fa fa-check"></i><b>3.2</b> Creating code chunks in R-Markdown</a></li>
<li class="chapter" data-level="3.3" data-path="chapter-1.html"><a href="chapter-1.html#running-chunnks"><i class="fa fa-check"></i><b>3.3</b> Running chunnks</a></li>
<li class="chapter" data-level="3.4" data-path="chapter-1.html"><a href="chapter-1.html#assignment"><i class="fa fa-check"></i><b>3.4</b> Assignment</a></li>
<li class="chapter" data-level="3.5" data-path="chapter-1.html"><a href="chapter-1.html#creating-d-which-is-a-b"><i class="fa fa-check"></i><b>3.5</b> Creating d, which is a + b</a></li>
<li class="chapter" data-level="3.6" data-path="chapter-1.html"><a href="chapter-1.html#exploring-data"><i class="fa fa-check"></i><b>3.6</b> Exploring Data<br></a></li>
<li class="chapter" data-level="3.7" data-path="chapter-1.html"><a href="chapter-1.html#mtcars-data"><i class="fa fa-check"></i><b>3.7</b> <code>mtcars</code> data</a></li>
<li class="chapter" data-level="3.8" data-path="chapter-1.html"><a href="chapter-1.html#pressure-data"><i class="fa fa-check"></i><b>3.8</b> <code>pressure</code> data</a></li>
<li class="chapter" data-level="3.9" data-path="chapter-1.html"><a href="chapter-1.html#graphing-data"><i class="fa fa-check"></i><b>3.9</b> Graphing Data</a></li>
<li class="chapter" data-level="3.10" data-path="chapter-1.html"><a href="chapter-1.html#a-note-on-arguments"><i class="fa fa-check"></i><b>3.10</b> A Note on Arguments</a></li>
<li class="chapter" data-level="3.11" data-path="chapter-1.html"><a href="chapter-1.html#aes-function-for-stating-your-x-and-y-axis"><i class="fa fa-check"></i><b>3.11</b> aes() function for stating your x and y axis</a></li>
<li class="chapter" data-level="3.12" data-path="chapter-1.html"><a href="chapter-1.html#the-power-of"><i class="fa fa-check"></i><b>3.12</b> The power of <code>+</code></a></li>
<li class="chapter" data-level="3.13" data-path="chapter-1.html"><a href="chapter-1.html#adding-features-to-your-ggplot-graph-using"><i class="fa fa-check"></i><b>3.13</b> Adding features to your ggplot graph using <code>+</code></a></li>
<li class="chapter" data-level="3.14" data-path="chapter-1.html"><a href="chapter-1.html#theme-function-for-modifying-components-of-your-graph"><i class="fa fa-check"></i><b>3.14</b> theme() function for modifying components of your graph</a></li>
<li class="chapter" data-level="3.15" data-path="chapter-1.html"><a href="chapter-1.html#labs-function-for-labeling-your-graph"><i class="fa fa-check"></i><b>3.15</b> labs() function for labeling your graph</a></li>
<li class="chapter" data-level="3.16" data-path="chapter-1.html"><a href="chapter-1.html#scale_color_gradient-function-for-using-a-color-gradient-on-mpg"><i class="fa fa-check"></i><b>3.16</b> scale_color_gradient() function for using a color gradient on mpg</a></li>
<li class="chapter" data-level="3.17" data-path="chapter-1.html"><a href="chapter-1.html#facet_grid-function-splitting-up-the-graph-by-a-group"><i class="fa fa-check"></i><b>3.17</b> facet_grid() function splitting up the graph by a group</a></li>
<li class="chapter" data-level="3.18" data-path="chapter-1.html"><a href="chapter-1.html#learning-more-about-libraries-and-functions"><i class="fa fa-check"></i><b>3.18</b> Learning More About Libraries and Functions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Workshop for Education Data Science Lesson 1</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chapter-1" class="section level1" number="3">
<h1><span class="header-section-number">Chapter 3</span> CHAPTER 1</h1>
<div id="loading-libraries" class="section level2" number="3.1">
<h2><span class="header-section-number">3.1</span> Loading Libraries</h2>
<p>First, let’s load the libraries you will use for this lesson. This is the first
thing you should do when writing an R-Markdown document. That way, you ensure
that you load all of the necessary libraries prior to running code</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="chapter-1.html#cb3-1"></a><span class="co"># install.libraries(&quot;gglot2&quot;) &lt;- installing libraries require double qoutations &quot;&quot;</span></span>
<span id="cb3-2"><a href="chapter-1.html#cb3-2"></a><span class="co"># install.libraries(&quot;rmdformats&quot;)</span></span>
<span id="cb3-3"><a href="chapter-1.html#cb3-3"></a><span class="kw">library</span>(ggplot2) <span class="co"># &lt;- loading libraries doesn&#39;t require double qoutations</span></span></code></pre></div>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 3.6.2</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="chapter-1.html#cb5-1"></a><span class="kw">library</span>(rmdformats) <span class="co"># for displaying the code in various html styles</span></span></code></pre></div>
<p><br><br></p>
<p>Before going into the ins-and-outs of coding in R, let’s get familiar with
how we can use R-markdown to create chunks of code.<br></p>
</div>
<div id="creating-code-chunks-in-r-markdown" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Creating code chunks in R-Markdown</h2>
<p>alt + command + i (mac)<br>
control + alt + i (windows)<br></p>
<p>Each chunk of code can be run individually.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="chapter-1.html#cb6-1"></a><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">3</span></span></code></pre></div>
<pre><code>## [1] 6</code></pre>
</div>
<div id="running-chunnks" class="section level2" number="3.3">
<h2><span class="header-section-number">3.3</span> Running chunnks</h2>
<p>You can run the chunk of code by clicking on the green arrow to the right
of the code.</p>
<p>Or use theses shortcuts&lt;br)
command + enter (mac)<br>
control + enter (windows)
<br><br>
## The very basics
##$ Simple Caluations</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="chapter-1.html#cb8-1"></a><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="chapter-1.html#cb10-1"></a><span class="dv">10</span><span class="op">/</span><span class="dv">2</span></span></code></pre></div>
<pre><code>## [1] 5</code></pre>
</div>
<div id="assignment" class="section level2" number="3.4">
<h2><span class="header-section-number">3.4</span> Assignment</h2>
<p>We assign values to variables by using <code>&lt;-</code><br>
Assigning a, b, and c</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="chapter-1.html#cb12-1"></a>a &lt;-<span class="st"> </span><span class="dv">2</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb12-2"><a href="chapter-1.html#cb12-2"></a>b &lt;-<span class="st"> </span><span class="dv">10</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span></span>
<span id="cb12-3"><a href="chapter-1.html#cb12-3"></a>c &lt;-<span class="st"> </span><span class="dv">4</span> <span class="op">+</span><span class="st"> </span><span class="dv">12</span></span></code></pre></div>
</div>
<div id="creating-d-which-is-a-b" class="section level2" number="3.5">
<h2><span class="header-section-number">3.5</span> Creating d, which is a + b</h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="chapter-1.html#cb13-1"></a>d &lt;-<span class="st"> </span>a <span class="op">+</span><span class="st"> </span>b</span>
<span id="cb13-2"><a href="chapter-1.html#cb13-2"></a>d</span></code></pre></div>
<pre><code>## [1] 16</code></pre>
<p><br><br></p>
</div>
<div id="exploring-data" class="section level2" number="3.6">
<h2><span class="header-section-number">3.6</span> Exploring Data<br></h2>
</div>
<div id="mtcars-data" class="section level2" number="3.7">
<h2><span class="header-section-number">3.7</span> <code>mtcars</code> data</h2>
<p>This data is pre-installed in R, and provides a quick way to fiddle around
with coding.</p>
<p>We can see the data by simply typing <code>mtcars</code></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="chapter-1.html#cb15-1"></a>mtcars</span></code></pre></div>
<pre><code>##                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
## Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
## Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
## Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
## Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
## Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
## Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
## Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
## Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
## Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
## Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
## Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
## Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
## AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
## Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
## Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
## Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
## Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
## Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
## Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
## Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
## Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
## Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2</code></pre>
<p>If you want to see less rows you can use the function <code>head</code></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="chapter-1.html#cb17-1"></a><span class="kw">head</span>(mtcars)</span></code></pre></div>
<pre><code>##                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
## Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1</code></pre>
</div>
<div id="pressure-data" class="section level2" number="3.8">
<h2><span class="header-section-number">3.8</span> <code>pressure</code> data</h2>
<p>We can see that there are only two variables in the pressure data</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="chapter-1.html#cb19-1"></a><span class="kw">head</span>(pressure)</span></code></pre></div>
<pre><code>##   temperature pressure
## 1           0   0.0002
## 2          20   0.0012
## 3          40   0.0060
## 4          60   0.0300
## 5          80   0.0900
## 6         100   0.2700</code></pre>
<p><br><br></p>
</div>
<div id="graphing-data" class="section level2" number="3.9">
<h2><span class="header-section-number">3.9</span> Graphing Data</h2>
<p>We can use the <code>plot</code> function to create a scatter plot for the <code>pressure</code> data</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="chapter-1.html#cb21-1"></a><span class="kw">plot</span>(pressure)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-10-1.png" width="672" />
<br><br></p>
</div>
<div id="a-note-on-arguments" class="section level2" number="3.10">
<h2><span class="header-section-number">3.10</span> A Note on Arguments</h2>
<p>Notice that functions in R always have () beside them<br>
head(mtcars)<br>
plot(pressure)<br>
<br>
In R, we put our arguments (which are extra things we want the argument to do)
inside these parentheses.</p>
<p><br><br>
## Intro to ggplot library and functions
Remember to make sure ggplot is loaded into R.<br>
You can do this by running the first chunk of this document, where it has the
code <code>library(ggplot2)</code><br>
<br>
We want to plot how miles per galon <code>mpg</code> is related to horsepower <code>hp</code>.
And then we want to split this up by cylnders <code>cyl</code>.<br><br></p>
<p>for ggplot, our first argument will be the dataset <code>mtcars</code></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="chapter-1.html#cb22-1"></a><span class="kw">ggplot</span>(mtcars)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-11-1.png" width="672" />
<br><br></p>
</div>
<div id="aes-function-for-stating-your-x-and-y-axis" class="section level2" number="3.11">
<h2><span class="header-section-number">3.11</span> aes() function for stating your x and y axis</h2>
<p>Within the ggplot() function, we’ll set up our parameters by using the <code>aes()</code> function
aes stands for asthetic. For this function, we want to define the x and y axis.</p>
<p>The x-axis will be <code>hp</code> and the y-axis will be <code>mpg</code></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="chapter-1.html#cb23-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg))</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-12-1.png" width="672" />
<br><br></p>
</div>
<div id="the-power-of" class="section level2" number="3.12">
<h2><span class="header-section-number">3.12</span> The power of <code>+</code></h2>
</div>
<div id="adding-features-to-your-ggplot-graph-using" class="section level2" number="3.13">
<h2><span class="header-section-number">3.13</span> Adding features to your ggplot graph using <code>+</code></h2>
<p>We can add new features by using other functions that are part of the ggplot
library.</p>
<p>We do this by using the <code>+</code> sign</p>
<p><br><br>
## geom() function for stating the kind of graph you want</p>
<p>geom stands for geometric unit.<br></p>
<p>Now let’s use the <code>geom</code> family of functions to state what kind of graph we want.<br></p>
<p>We want a scatterplot, so we are going to use the function <code>geom_point()</code><br></p>
<p>No arguments are required for <code>geom_point()</code></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="chapter-1.html#cb24-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb24-2"><a href="chapter-1.html#cb24-2"></a><span class="st"> </span><span class="kw">geom_point</span>() </span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-13-1.png" width="672" />
<br><br></p>
</div>
<div id="theme-function-for-modifying-components-of-your-graph" class="section level2" number="3.14">
<h2><span class="header-section-number">3.14</span> theme() function for modifying components of your graph</h2>
<p>let’s set the size of the text by 20 using <code>text = element_text(size = 20)</code></p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="chapter-1.html#cb25-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb25-2"><a href="chapter-1.html#cb25-2"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb25-3"><a href="chapter-1.html#cb25-3"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>))</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-14-1.png" width="672" />
<br><br></p>
</div>
<div id="labs-function-for-labeling-your-graph" class="section level2" number="3.15">
<h2><span class="header-section-number">3.15</span> labs() function for labeling your graph</h2>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="chapter-1.html#cb26-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb26-2"><a href="chapter-1.html#cb26-2"></a><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb26-3"><a href="chapter-1.html#cb26-3"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>)) <span class="op">+</span></span>
<span id="cb26-4"><a href="chapter-1.html#cb26-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Horsepower&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;MPG&quot;</span>)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-15-1.png" width="672" />
<br><br></p>
</div>
<div id="scale_color_gradient-function-for-using-a-color-gradient-on-mpg" class="section level2" number="3.16">
<h2><span class="header-section-number">3.16</span> scale_color_gradient() function for using a color gradient on mpg</h2>
<p>We want the low mpg to be blue and the high mpg to be red.<br></p>
<p>IMPORTANT! In order to make this function work, you have to state which variable
you want it to color. Let’s color <code>mpg</code>. <br></p>
<p>In order to state this, we have to go back to the <code>aes()</code> function and write an additional argument. Remember, arguments are separated by <code>,</code><br></p>
<p>So your aes code should look like this now <code>aes(x = hp, y = mpg, color = mpg)</code></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="chapter-1.html#cb27-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg, <span class="dt">color =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb27-2"><a href="chapter-1.html#cb27-2"></a><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb27-3"><a href="chapter-1.html#cb27-3"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>)) <span class="op">+</span></span>
<span id="cb27-4"><a href="chapter-1.html#cb27-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Horsepower&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;MPG&quot;</span>) <span class="op">+</span></span>
<span id="cb27-5"><a href="chapter-1.html#cb27-5"></a><span class="st">  </span><span class="kw">scale_color_gradient</span>(<span class="dt">low =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-16-1.png" width="672" />
<br><br></p>
</div>
<div id="facet_grid-function-splitting-up-the-graph-by-a-group" class="section level2" number="3.17">
<h2><span class="header-section-number">3.17</span> facet_grid() function splitting up the graph by a group</h2>
<p>We want to split our graph up by the variable <code>cyl</code><br></p>
<p>use <code>.~cyl</code> to get a horizontal verison</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="chapter-1.html#cb28-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg, <span class="dt">color =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb28-2"><a href="chapter-1.html#cb28-2"></a><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb28-3"><a href="chapter-1.html#cb28-3"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>)) <span class="op">+</span></span>
<span id="cb28-4"><a href="chapter-1.html#cb28-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Horsepower&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;MPG&quot;</span>) <span class="op">+</span></span>
<span id="cb28-5"><a href="chapter-1.html#cb28-5"></a><span class="st">  </span><span class="kw">scale_color_gradient</span>(<span class="dt">low =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb28-6"><a href="chapter-1.html#cb28-6"></a><span class="st">  </span><span class="kw">facet_grid</span>(.<span class="op">~</span>cyl)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-17-1.png" width="672" />
<br><br></p>
<p>use <code>cyl~.</code> to get a vertical verison.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="chapter-1.html#cb29-1"></a><span class="kw">ggplot</span>(mtcars, <span class="kw">aes</span>(<span class="dt">x =</span> hp, <span class="dt">y =</span> mpg, <span class="dt">color =</span> mpg)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb29-2"><a href="chapter-1.html#cb29-2"></a><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></span>
<span id="cb29-3"><a href="chapter-1.html#cb29-3"></a><span class="st">  </span><span class="kw">theme</span>(<span class="dt">text =</span> <span class="kw">element_text</span>(<span class="dt">size =</span> <span class="dv">20</span>)) <span class="op">+</span></span>
<span id="cb29-4"><a href="chapter-1.html#cb29-4"></a><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Horsepower&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;MPG&quot;</span>) <span class="op">+</span></span>
<span id="cb29-5"><a href="chapter-1.html#cb29-5"></a><span class="st">  </span><span class="kw">scale_color_gradient</span>(<span class="dt">low =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">high =</span> <span class="st">&quot;blue&quot;</span>) <span class="op">+</span></span>
<span id="cb29-6"><a href="chapter-1.html#cb29-6"></a><span class="st">  </span><span class="kw">facet_grid</span>(cyl<span class="op">~</span>.)</span></code></pre></div>
<p><img src="r-4-la_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p><br><br></p>
</div>
<div id="learning-more-about-libraries-and-functions" class="section level2" number="3.18">
<h2><span class="header-section-number">3.18</span> Learning More About Libraries and Functions</h2>
<p>If you want to see more information about what you can do with a library like
ggplot2, you can put <code>?</code> in front of the name of the library.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="chapter-1.html#cb30-1"></a>?ggplot2</span></code></pre></div>
<p><br><br>
If you want to know more about how to use a specific function
put a ? in front of the function name</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="chapter-1.html#cb31-1"></a>?<span class="kw">ggplot</span>()</span></code></pre></div>
<p><br><br>
You can even do this with sub-functions, like <code>element_text()</code></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="chapter-1.html#cb32-1"></a>?<span class="kw">element_text</span>()</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["r-4-la.pdf", "r-4-la.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
